"""empty message

Revision ID: 078fd395ee5c
Revises: 
Create Date: 2026-05-22 10:21:30.410162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078fd395ee5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('basic_salary', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('payroll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allowance', sa.Float(), nullable=False),
    sa.Column('deduction', sa.Float(), nullable=False),
    sa.Column('overtime', sa.Float(), nullable=False),
    sa.Column('salary_snapshot', sa.Float(), nullable=False),
    sa.Column('employee_name', sa.String(length=100), nullable=False),
    sa.Column('net_pay', sa.Float(), nullable=False),
    sa.Column('payroll_date', sa.String(length=100), nullable=False),
    sa.Column('payroll_period', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payroll')
    op.drop_table('user')
    op.drop_table('post')
    # ### end Alembic commands ###
